export default function IncidentReportPanel({ llmReport }) {
  if (!llmReport) return null;

  const { source, sections, text, error } = llmReport;

  return (
    <section className="panel report-panel">
      <div className="panel__title">
        <h2>Incident Report</h2>
        {source === "fallback" ? (
          <p className="report-panel__source report-panel__source--fallback">
            Deterministic fallback report (LLM unavailable{error ? `: ${error}` : ""})
          </p>
        ) : (
          <p className="report-panel__source report-panel__source--llm">Generated by LLM from structured evidence only</p>
        )}
      </div>
      {sections ? (
        <div className="report-panel__sections">
          {Object.entries(sections).map(([heading, body]) => (
            <div key={heading} className="report-panel__section">
              <h4>{heading}</h4>
              <p>{body}</p>
            </div>
          ))}
        </div>
      ) : (
        <div className="report-panel__text">{text}</div>
      )}
    </section>
  );
}
